FROM registry:2.6.1

COPY registry.* /certs/
ENV REGISTRY_HTTP_TLS_CERTIFICATE /certs/registry.crt
ENV REGISTRY_HTTP_TLS_KEY /certs/registry.key

COPY htpasswd /auth/
ENV REGISTRY_AUTH htpasswd
ENV REGISTRY_AUTH_HTPASSWD_REALM Registry Realm
ENV REGISTRY_AUTH_HTPASSWD_PATH /auth/htpasswd